FROM node:20-alpine AS builder

WORKDIR /app

COPY tma/package.json ./tma/
RUN cd tma && npm install

COPY tma ./tma
RUN cd tma && npm run build

FROM nginx:1.27-alpine

COPY deploy/docker/nginx.tma.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/tma/dist /usr/share/nginx/html

EXPOSE 80
