export const DIANA_PRE_EDITORIAL_IMAGE_SNAPSHOT = {
  createdAt: "2026-03-20",
  description:
    "Pre-editorial-image swap snapshot of Diana's Camille-style shell assets, collage presets, and hero options.",
  heroPortraitOptions: [
    {
      id: "noir",
      label: "Noir",
      path: "/diana/Diana%203.png",
      objectPosition: "82% 13%",
      scale: 1.8,
    },
    {
      id: "forest",
      label: "Forest",
      path: "/diana/Diana%201.png",
      objectPosition: "0% 11%",
      scale: 1.55,
    },
    {
      id: "shore",
      label: "Shore",
      path: "/diana/Diana%2014.jpg",
      objectPosition: "6% 39%",
      scale: 1.56,
    },
    {
      id: "noir-wide",
      label: "Noir Wide",
      path: "/diana/upscaled/hero-noir-gpt-image-1-5-landscape.png",
      objectPosition: "85% 0%",
      scale: 1.8,
    },
    {
      id: "forest-wide",
      label: "Forest Wide",
      path: "/diana/upscaled/hero-forest-gpt-image-1-5-landscape.png",
      objectPosition: "19% 10%",
      scale: 1.79,
    },
    {
      id: "shore-wide",
      label: "Shore Wide",
      path: "/diana/upscaled/hero-shore-gpt-image-1-5-landscape.png",
      objectPosition: "54% 32%",
      scale: 1.54,
    },
  ],
  assets: {
    heroPortrait: "/diana/Diana%203.png",
    originPortrait: "/diana/Diana%201.png",
    ascensionPortrait: "/diana/Diana%2014.jpg",
    staticScene: "/diana/forge-static.svg",
  },
  collageViews: [
    {
      id: "view-1",
      label: "pilgrimage",
      cards: [
        {
          id: "view-1-forest-wide",
          path: "/diana/upscaled/hero-forest-gpt-image-1-5-landscape.png",
          alt: "Diana by the water in a wide forest-toned portrait",
          caption: "forest",
          desktop: {
            x: 588,
            y: 52,
            width: 404,
            height: 254,
            rotation: -2,
            zIndex: 1,
            objectPosition: "19% 10%",
          },
          mobile: {
            x: 52,
            y: 18,
            width: 264,
            height: 162,
            rotation: -2,
            zIndex: 1,
            objectPosition: "19% 10%",
          },
        },
        {
          id: "view-1-noir",
          path: "/diana/Diana%203.png",
          alt: "Diana reclining in a red dress",
          caption: "noir",
          desktop: {
            x: 944,
            y: 100,
            width: 248,
            height: 186,
            rotation: 5,
            zIndex: 3,
            objectPosition: "82% 13%",
          },
          mobile: {
            x: 220,
            y: 86,
            width: 160,
            height: 118,
            rotation: 5,
            zIndex: 3,
            objectPosition: "82% 13%",
          },
        },
        {
          id: "view-1-ritual-white",
          path: "/diana/Diana%201.png",
          alt: "Diana standing in white outdoors",
          caption: "origin",
          desktop: {
            x: 500,
            y: 352,
            width: 186,
            height: 252,
            rotation: -7,
            zIndex: 5,
            objectPosition: "0% 11%",
          },
          mobile: {
            x: -8,
            y: 196,
            width: 142,
            height: 196,
            rotation: -7,
            zIndex: 5,
            objectPosition: "0% 11%",
          },
        },
        {
          id: "view-1-portrait-five",
          path: "/diana/Diana%205.png",
          alt: "Diana in a soft portrait",
          caption: "threshold",
          desktop: {
            x: 344,
            y: 136,
            width: 202,
            height: 280,
            rotation: 4,
            zIndex: 6,
          },
          mobile: {
            x: 136,
            y: 176,
            width: 132,
            height: 188,
            rotation: 4,
            zIndex: 6,
          },
        },
        {
          id: "view-1-smile",
          path: "/diana/Diana%2012.jpg",
          alt: "Diana smiling upward",
          caption: "return",
          desktop: {
            x: 786,
            y: 334,
            width: 234,
            height: 308,
            rotation: -4,
            zIndex: 4,
          },
          mobile: {
            x: 186,
            y: 286,
            width: 152,
            height: 204,
            rotation: -4,
            zIndex: 4,
          },
        },
        {
          id: "view-1-noir-wide",
          path: "/diana/upscaled/hero-noir-gpt-image-1-5-landscape.png",
          alt: "Wide noir portrait of Diana in red",
          caption: "shadowbreaker",
          desktop: {
            x: 1018,
            y: 426,
            width: 284,
            height: 176,
            rotation: 4,
            zIndex: 2,
            objectPosition: "85% 0%",
          },
          mobile: {
            x: 104,
            y: 470,
            width: 220,
            height: 136,
            rotation: 4,
            zIndex: 2,
            objectPosition: "85% 0%",
          },
        },
      ],
    },
    {
      id: "view-2",
      label: "thresholds",
      cards: [
        {
          id: "view-2-noir-wide",
          path: "/diana/upscaled/hero-noir-gpt-image-1-5-landscape.png",
          alt: "Wide noir portrait of Diana in red",
          caption: "cathedral",
          desktop: {
            x: 614,
            y: 84,
            width: 362,
            height: 224,
            rotation: 3,
            zIndex: 1,
            objectPosition: "85% 0%",
          },
          mobile: {
            x: 26,
            y: 22,
            width: 276,
            height: 168,
            rotation: 3,
            zIndex: 1,
            objectPosition: "85% 0%",
          },
        },
        {
          id: "view-2-shore-portrait",
          path: "/diana/Diana%2014.jpg",
          alt: "Diana on the shoreline at dusk",
          caption: "shore",
          desktop: {
            x: 980,
            y: 92,
            width: 218,
            height: 292,
            rotation: -5,
            zIndex: 4,
            objectPosition: "6% 39%",
          },
          mobile: {
            x: 196,
            y: 110,
            width: 158,
            height: 212,
            rotation: -5,
            zIndex: 4,
            objectPosition: "6% 39%",
          },
        },
        {
          id: "view-2-water",
          path: "/diana/Diana%208.jpg",
          alt: "Diana in a lakeside landscape portrait",
          caption: "grief tide",
          desktop: {
            x: 760,
            y: 338,
            width: 270,
            height: 180,
            rotation: 6,
            zIndex: 2,
          },
          mobile: {
            x: 72,
            y: 222,
            width: 220,
            height: 144,
            rotation: 6,
            zIndex: 2,
          },
        },
        {
          id: "view-2-portrait-six",
          path: "/diana/Diana%206.png",
          alt: "Diana in a poised portrait",
          caption: "armor",
          desktop: {
            x: 1036,
            y: 396,
            width: 208,
            height: 282,
            rotation: 2,
            zIndex: 5,
          },
          mobile: {
            x: 216,
            y: 374,
            width: 132,
            height: 186,
            rotation: 2,
            zIndex: 5,
          },
        },
        {
          id: "view-2-portrait-eleven",
          path: "/diana/Diana%2011.jpg",
          alt: "Diana in a close portrait",
          caption: "witness",
          desktop: {
            x: 414,
            y: 292,
            width: 194,
            height: 252,
            rotation: -3,
            zIndex: 6,
          },
          mobile: {
            x: -10,
            y: 318,
            width: 150,
            height: 198,
            rotation: -3,
            zIndex: 6,
          },
        },
        {
          id: "view-2-shore-wide",
          path: "/diana/upscaled/hero-shore-gpt-image-1-5-landscape.png",
          alt: "Wide shoreline portrait of Diana",
          caption: "return path",
          desktop: {
            x: 638,
            y: 508,
            width: 320,
            height: 190,
            rotation: -6,
            zIndex: 3,
            objectPosition: "54% 32%",
          },
          mobile: {
            x: 52,
            y: 522,
            width: 248,
            height: 146,
            rotation: -6,
            zIndex: 3,
            objectPosition: "54% 32%",
          },
        },
      ],
    },
    {
      id: "view-3",
      label: "return",
      cards: [
        {
          id: "view-3-forest-wide",
          path: "/diana/upscaled/hero-forest-gpt-image-1-5-landscape.png",
          alt: "Wide forest-toned portrait of Diana",
          caption: "pilgrimage",
          desktop: {
            x: 726,
            y: 68,
            width: 428,
            height: 262,
            rotation: 2,
            zIndex: 1,
            objectPosition: "19% 10%",
          },
          mobile: {
            x: 32,
            y: 18,
            width: 290,
            height: 178,
            rotation: 2,
            zIndex: 1,
            objectPosition: "19% 10%",
          },
        },
        {
          id: "view-3-portrait-thirteen",
          path: "/diana/Diana%2013.jpg",
          alt: "Diana in a bright close portrait",
          caption: "joy",
          desktop: {
            x: 974,
            y: 178,
            width: 232,
            height: 310,
            rotation: -4,
            zIndex: 4,
          },
          mobile: {
            x: 198,
            y: 126,
            width: 162,
            height: 218,
            rotation: -4,
            zIndex: 4,
          },
        },
        {
          id: "view-3-portrait-two",
          path: "/diana/Diana%202.png",
          alt: "Diana in an editorial portrait",
          caption: "myth",
          desktop: {
            x: 530,
            y: 150,
            width: 184,
            height: 252,
            rotation: 7,
            zIndex: 6,
          },
          mobile: {
            x: 18,
            y: 196,
            width: 136,
            height: 188,
            rotation: 7,
            zIndex: 6,
          },
        },
        {
          id: "view-3-smile-ten",
          path: "/diana/Diana%2010.jpg",
          alt: "Diana in a warm smiling portrait",
          caption: "breath",
          desktop: {
            x: 850,
            y: 438,
            width: 250,
            height: 176,
            rotation: 5,
            zIndex: 3,
          },
          mobile: {
            x: 92,
            y: 418,
            width: 214,
            height: 148,
            rotation: 5,
            zIndex: 3,
          },
        },
        {
          id: "view-3-landscape-seven",
          path: "/diana/Diana%207.jpg",
          alt: "Diana outdoors in a soft landscape portrait",
          caption: "softness",
          desktop: {
            x: 624,
            y: 386,
            width: 212,
            height: 284,
            rotation: -7,
            zIndex: 5,
          },
          mobile: {
            x: 174,
            y: 290,
            width: 138,
            height: 190,
            rotation: -7,
            zIndex: 5,
          },
        },
        {
          id: "view-3-portrait-fifteen",
          path: "/diana/Diana%2015.jpg",
          alt: "Diana in an expressive close portrait",
          caption: "witnessing",
          desktop: {
            x: 1090,
            y: 502,
            width: 176,
            height: 236,
            rotation: 3,
            zIndex: 2,
          },
          mobile: {
            x: -2,
            y: 532,
            width: 126,
            height: 170,
            rotation: 3,
            zIndex: 2,
          },
        },
      ],
    },
    {
      id: "view-4",
      label: "witness",
      cards: [
        {
          id: "view-4-shore-wide",
          path: "/diana/upscaled/hero-shore-gpt-image-1-5-landscape.png",
          alt: "Wide shoreline portrait of Diana",
          caption: "shoreline",
          desktop: {
            x: 666,
            y: 54,
            width: 452,
            height: 270,
            rotation: -3,
            zIndex: 1,
            objectPosition: "54% 32%",
          },
          mobile: {
            x: 34,
            y: 18,
            width: 290,
            height: 174,
            rotation: -3,
            zIndex: 1,
            objectPosition: "54% 32%",
          },
        },
        {
          id: "view-4-water-nine",
          path: "/diana/Diana%209.jpg",
          alt: "Diana framed against water",
          caption: "tide",
          desktop: {
            x: 1046,
            y: 112,
            width: 210,
            height: 294,
            rotation: 6,
            zIndex: 4,
          },
          mobile: {
            x: 194,
            y: 118,
            width: 154,
            height: 214,
            rotation: 6,
            zIndex: 4,
          },
        },
        {
          id: "view-4-portrait-four",
          path: "/diana/Diana%204.png",
          alt: "Diana in a strong editorial pose",
          caption: "ferocity",
          desktop: {
            x: 504,
            y: 120,
            width: 194,
            height: 260,
            rotation: -8,
            zIndex: 6,
          },
          mobile: {
            x: 4,
            y: 180,
            width: 138,
            height: 188,
            rotation: -8,
            zIndex: 6,
          },
        },
        {
          id: "view-4-portrait-fifteen",
          path: "/diana/Diana%2015.jpg",
          alt: "Diana in an expressive close portrait",
          caption: "repair",
          desktop: {
            x: 814,
            y: 356,
            width: 222,
            height: 300,
            rotation: 4,
            zIndex: 5,
          },
          mobile: {
            x: 172,
            y: 294,
            width: 146,
            height: 196,
            rotation: 4,
            zIndex: 5,
          },
        },
        {
          id: "view-4-portrait-two",
          path: "/diana/Diana%202.png",
          alt: "Diana in an editorial portrait",
          caption: "returning self",
          desktop: {
            x: 1098,
            y: 430,
            width: 170,
            height: 232,
            rotation: -2,
            zIndex: 3,
          },
          mobile: {
            x: -8,
            y: 540,
            width: 120,
            height: 166,
            rotation: -2,
            zIndex: 3,
          },
        },
        {
          id: "view-4-smile-ten",
          path: "/diana/Diana%2010.jpg",
          alt: "Diana in a warm smiling portrait",
          caption: "afterglow",
          desktop: {
            x: 564,
            y: 454,
            width: 236,
            height: 172,
            rotation: 7,
            zIndex: 2,
          },
          mobile: {
            x: 76,
            y: 430,
            width: 204,
            height: 144,
            rotation: 7,
            zIndex: 2,
          },
        },
      ],
    },
  ],
} as const;
